/**
 * Golden fixtures: one real response per platform, parsed and asserted in full.
 *
 * Every way this scraper breaks, it breaks quietly. A school re-themes its schedule page
 * and the row selector matches nothing; a JSON field is renamed and every score comes
 * back null; an opponent stops resolving and half a season files itself under two names.
 * None of that raises. The stage exits 0, writes fewer or emptier rows than it did
 * yesterday, and the pipeline carries on to rate teams on a dataset that quietly lost a
 * conference. The only way to see it is to have written the answer down first.
 *
 * So each of the six fixtures in `packages/parsers/src/__fixtures__` is parsed here and
 * compared against its complete output — every row, every field, serialised as JSON so
 * that nothing can be added, dropped or reordered without the diff saying so. Asserting
 * a count instead would pass for any of the failures above that keeps the row count.
 *
 * The parsers are driven exactly as `fetch_schedules_parallel.ts` and
 * `fetch_boxscores_from_csv.ts` drive them, down to the real `TeamNameResolver` built
 * from `data/teams`. That is deliberate: canonicalisation is part of what silently
 * degrades, and a test that injects an empty resolver would not notice an alias
 * disappearing. It does mean an inventory edit can move these expectations — legitimately
 * — so read the diff rather than regenerating past it.
 *
 * Every fixture is the 2025 season, which is over. A correct parser returns these exact
 * rows forever.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'fs';
import * as path from 'path';
import { Game, GameSchema, PlayerStat, PlayerStatSchema } from '@ncaa/shared';
import {
    SidearmBoxScoreParser,
    SidearmParser,
    WmtBoxScoreParser,
    WmtParser,
    WmtWordpressParser
} from '@ncaa/parsers';
import { REPO_ROOT } from '@ncaa/storage';
import { buildTeamNameResolver, loadAllTeams } from '../utils/teams';

const FIXTURES = path.join(REPO_ROOT, 'packages/parsers/src/__fixtures__');
const fixture = (name: string): string => fs.readFileSync(path.join(FIXTURES, name), 'utf8');

/** The resolver the pipeline runs with: every alias of every school in the inventory. */
const resolver = buildTeamNameResolver(loadAllTeams());

/**
 * One line per row, lossless.
 *
 * `JSON.stringify` rather than a hand-written formatter because a formatter is a second
 * place to forget a field: it would keep passing after the parser stopped setting
 * `game_type`, which is the exact class of silence these fixtures exist to break.
 */
const lines = (rows: unknown[]): string[] => rows.map(row => JSON.stringify(row));

/** Rows the pipeline would refuse to store are a failure however well they compare. */
function assertValidGames(games: Game[]): void {
    for (const game of games) {
        const parsed = GameSchema.safeParse(game);
        assert.ok(parsed.success, `${game.game_id}: ${JSON.stringify((parsed as any).error?.issues)}`);
    }
}

function assertValidPlayerStats(stats: PlayerStat[]): void {
    for (const stat of stats) {
        const parsed = PlayerStatSchema.safeParse(stat);
        assert.ok(parsed.success, `${stat.player_key}: ${JSON.stringify((parsed as any).error?.issues)}`);
    }
}


/** Duke's 2025 season as `SidearmParser` reads it: 23 fixtures, poll markers still on the
 * opponent (the pipeline strips those later), and a box-score link on every game that
 * has one. Ranked opponents, both scorelines of a draw, and the three NCAA tournament
 * rounds are all in here, so a parser that loses any one of those loses this test. */
const DUKE_SCHEDULE: string[] = [
    "{\"game_id\":\"sidearm-2025-08-08-Coastal-Carolina-Duke\",\"date\":\"2025-08-08\",\"home_team_name\":\"Coastal Carolina\",\"away_team_name\":\"Duke\",\"home_score\":1,\"away_score\":1,\"location_type\":\"away\",\"status\":\"final\",\"source_urls\":{},\"dedupe_key\":\"2025-08-08-Coastal-Carolina-Duke\"}",
    "{\"game_id\":\"sidearm-2025-08-12-UNC-Asheville-Duke\",\"date\":\"2025-08-12\",\"home_team_name\":\"UNC Asheville\",\"away_team_name\":\"Duke\",\"home_score\":1,\"away_score\":5,\"location_type\":\"away\",\"status\":\"final\",\"source_urls\":{},\"dedupe_key\":\"2025-08-12-Duke-UNC-Asheville\"}",
    "{\"game_id\":\"sidearm-2025-08-16-Duke-James-Madison\",\"date\":\"2025-08-16\",\"home_team_name\":\"Duke\",\"away_team_name\":\"James Madison\",\"home_score\":3,\"away_score\":0,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{},\"dedupe_key\":\"2025-08-16-Duke-James-Madison\"}",
    "{\"game_id\":\"sidearm-2025-08-21-Duke-#10-San-Diego\",\"date\":\"2025-08-21\",\"home_team_name\":\"Duke\",\"away_team_name\":\"#10 San Diego\",\"home_score\":2,\"away_score\":1,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"boxscore_url\":\"https://goduke.com/sports/mens-soccer/stats/2025/san-diego/boxscore/24391\"},\"dedupe_key\":\"2025-08-21-#10-San-Diego-Duke\"}",
    "{\"game_id\":\"sidearm-2025-08-24-Duke-UC-San-Diego\",\"date\":\"2025-08-24\",\"home_team_name\":\"Duke\",\"away_team_name\":\"UC San Diego\",\"home_score\":1,\"away_score\":0,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"boxscore_url\":\"https://goduke.com/sports/mens-soccer/stats/2025/uc-san-diego/boxscore/24392\"},\"dedupe_key\":\"2025-08-24-Duke-UC-San-Diego\"}",
    "{\"game_id\":\"sidearm-2025-08-31-Furman-Duke\",\"date\":\"2025-08-31\",\"home_team_name\":\"Furman\",\"away_team_name\":\"Duke\",\"home_score\":1,\"away_score\":1,\"location_type\":\"away\",\"status\":\"final\",\"source_urls\":{\"boxscore_url\":\"https://goduke.com/sports/mens-soccer/stats/2025/furman/boxscore/24393\"},\"dedupe_key\":\"2025-08-31-Duke-Furman\"}",
    "{\"game_id\":\"sidearm-2025-09-05-Georgetown-Duke\",\"date\":\"2025-09-05\",\"home_team_name\":\"Georgetown\",\"away_team_name\":\"Duke\",\"home_score\":2,\"away_score\":2,\"location_type\":\"away\",\"status\":\"final\",\"source_urls\":{\"boxscore_url\":\"https://goduke.com/sports/mens-soccer/stats/2025/georgetown/boxscore/24394\"},\"dedupe_key\":\"2025-09-05-Duke-Georgetown\"}",
    "{\"game_id\":\"sidearm-2025-09-14-California-Duke\",\"date\":\"2025-09-14\",\"home_team_name\":\"California\",\"away_team_name\":\"Duke\",\"home_score\":1,\"away_score\":1,\"location_type\":\"away\",\"status\":\"final\",\"source_urls\":{\"boxscore_url\":\"https://goduke.com/sports/mens-soccer/stats/2025/california/boxscore/24395\"},\"dedupe_key\":\"2025-09-14-California-Duke\"}",
    "{\"game_id\":\"sidearm-2025-09-19-Duke-Syracuse\",\"date\":\"2025-09-19\",\"home_team_name\":\"Duke\",\"away_team_name\":\"Syracuse\",\"home_score\":2,\"away_score\":0,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"boxscore_url\":\"https://goduke.com/sports/mens-soccer/stats/2025/syracuse/boxscore/24396\"},\"dedupe_key\":\"2025-09-19-Duke-Syracuse\"}",
    "{\"game_id\":\"sidearm-2025-09-23-Duke-Howard\",\"date\":\"2025-09-23\",\"home_team_name\":\"Duke\",\"away_team_name\":\"Howard\",\"home_score\":8,\"away_score\":0,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"boxscore_url\":\"https://goduke.com/sports/mens-soccer/stats/2025/howard/boxscore/24397\"},\"dedupe_key\":\"2025-09-23-Duke-Howard\"}",
    "{\"game_id\":\"sidearm-2025-09-26-Duke-Louisville\",\"date\":\"2025-09-26\",\"home_team_name\":\"Duke\",\"away_team_name\":\"Louisville\",\"home_score\":1,\"away_score\":0,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"boxscore_url\":\"https://goduke.com/sports/mens-soccer/stats/2025/louisville/boxscore/24398\"},\"dedupe_key\":\"2025-09-26-Duke-Louisville\"}",
    "{\"game_id\":\"sidearm-2025-09-30-Duke-Averett\",\"date\":\"2025-09-30\",\"home_team_name\":\"Duke\",\"away_team_name\":\"Averett\",\"home_score\":10,\"away_score\":0,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"boxscore_url\":\"https://goduke.com/sports/mens-soccer/stats/2025/averett/boxscore/24399\"},\"dedupe_key\":\"2025-09-30-Averett-Duke\"}",
    "{\"game_id\":\"sidearm-2025-10-03-Duke-Pitt\",\"date\":\"2025-10-03\",\"home_team_name\":\"Duke\",\"away_team_name\":\"Pitt\",\"home_score\":4,\"away_score\":0,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"boxscore_url\":\"https://goduke.com/sports/mens-soccer/stats/2025/pitt/boxscore/24400\"},\"dedupe_key\":\"2025-10-03-Duke-Pitt\"}",
    "{\"game_id\":\"sidearm-2025-10-07-Duke-Elon\",\"date\":\"2025-10-07\",\"home_team_name\":\"Duke\",\"away_team_name\":\"Elon\",\"home_score\":1,\"away_score\":1,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"boxscore_url\":\"https://goduke.com/sports/mens-soccer/stats/2025/elon/boxscore/24401\"},\"dedupe_key\":\"2025-10-07-Duke-Elon\"}",
    "{\"game_id\":\"sidearm-2025-10-10-Boston-College-Duke\",\"date\":\"2025-10-10\",\"home_team_name\":\"Boston College\",\"away_team_name\":\"Duke\",\"home_score\":0,\"away_score\":0,\"location_type\":\"away\",\"status\":\"final\",\"source_urls\":{\"boxscore_url\":\"https://goduke.com/sports/mens-soccer/stats/2025/boston-college/boxscore/24402\"},\"dedupe_key\":\"2025-10-10-Boston-College-Duke\"}",
    "{\"game_id\":\"sidearm-2025-10-17-Clemson-Duke\",\"date\":\"2025-10-17\",\"home_team_name\":\"Clemson\",\"away_team_name\":\"Duke\",\"home_score\":3,\"away_score\":0,\"location_type\":\"away\",\"status\":\"final\",\"source_urls\":{\"boxscore_url\":\"https://goduke.com/sports/mens-soccer/stats/2025/clemson/boxscore/24403\"},\"dedupe_key\":\"2025-10-17-Clemson-Duke\"}",
    "{\"game_id\":\"sidearm-2025-10-21-Duke-Queens\",\"date\":\"2025-10-21\",\"home_team_name\":\"Duke\",\"away_team_name\":\"Queens\",\"home_score\":0,\"away_score\":0,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"boxscore_url\":\"https://goduke.com/sports/mens-soccer/stats/2025/queens/boxscore/24404\"},\"dedupe_key\":\"2025-10-21-Duke-Queens\"}",
    "{\"game_id\":\"sidearm-2025-10-25-Duke-#3-NC-State\",\"date\":\"2025-10-25\",\"home_team_name\":\"Duke\",\"away_team_name\":\"#3 NC State\",\"home_score\":0,\"away_score\":2,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"boxscore_url\":\"https://goduke.com/sports/mens-soccer/stats/2025/nc-state/boxscore/24405\"},\"dedupe_key\":\"2025-10-25-#3-NC-State-Duke\"}",
    "{\"game_id\":\"sidearm-2025-10-31-North-Carolina-Duke\",\"date\":\"2025-10-31\",\"home_team_name\":\"North Carolina\",\"away_team_name\":\"Duke\",\"home_score\":0,\"away_score\":2,\"location_type\":\"away\",\"status\":\"final\",\"source_urls\":{\"boxscore_url\":\"https://goduke.com/sports/mens-soccer/stats/2025/north-carolina/boxscore/24406\"},\"dedupe_key\":\"2025-10-31-Duke-North-Carolina\"}",
    "{\"game_id\":\"sidearm-2025-11-05-Duke-California\",\"date\":\"2025-11-05\",\"home_team_name\":\"Duke\",\"away_team_name\":\"California\",\"home_score\":0,\"away_score\":2,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"boxscore_url\":\"https://goduke.com/sports/mens-soccer/stats/2025/california/boxscore/24562\"},\"dedupe_key\":\"2025-11-05-California-Duke\"}",
    "{\"game_id\":\"sidearm-2025-11-20-Duke-FDU\",\"date\":\"2025-11-20\",\"home_team_name\":\"Duke\",\"away_team_name\":\"FDU\",\"home_score\":1,\"away_score\":0,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"boxscore_url\":\"https://goduke.com/sports/mens-soccer/stats/2025/fdu/boxscore/24699\"},\"dedupe_key\":\"2025-11-20-Duke-FDU\"}",
    "{\"game_id\":\"sidearm-2025-11-23-#3-Princeton-Duke\",\"date\":\"2025-11-23\",\"home_team_name\":\"#3 Princeton\",\"away_team_name\":\"Duke\",\"home_score\":1,\"away_score\":2,\"location_type\":\"away\",\"status\":\"final\",\"source_urls\":{\"boxscore_url\":\"https://goduke.com/sports/mens-soccer/stats/2025/princeton/boxscore/24756\"},\"dedupe_key\":\"2025-11-23-#3-Princeton-Duke\"}",
    "{\"game_id\":\"sidearm-2025-11-30-#14-Akron-Duke\",\"date\":\"2025-11-30\",\"home_team_name\":\"#14 Akron\",\"away_team_name\":\"Duke\",\"home_score\":2,\"away_score\":0,\"location_type\":\"away\",\"status\":\"final\",\"source_urls\":{\"boxscore_url\":\"https://goduke.com/sports/mens-soccer/stats/2025/akron/boxscore/24759\"},\"dedupe_key\":\"2025-11-30-#14-Akron-Duke\"}"
];


/** Clemson's 2025 season from the WMT `/website-api` payload.
 *
 * The payload holds 25 events; five are spring 2026 fixtures that `seasonYear` drops.
 * The three exhibitions keep `game_type: "exhibition"` — WMT is the only source that
 * states it rather than writing it into the opponent's name. The Indiana game is stamped
 * `2025-08-22T00:00:00Z` and belongs to 2025-08-21 in Eastern time: get the zone wrong
 * and this row stops deduping against Indiana's own copy of the same fixture. */
const CLEMSON_SCHEDULE: string[] = [
    "{\"game_id\":\"wmt-2025-08-09-Charlotte-Clemson\",\"date\":\"2025-08-09\",\"home_team_name\":\"Clemson\",\"away_team_name\":\"Charlotte\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":null,\"away_score\":null,\"location_type\":\"home\",\"game_type\":\"exhibition\",\"status\":\"scheduled\",\"source_urls\":{\"schedule_url\":\"https://clemsontigers.com/sports/mens-soccer/schedule\"},\"dedupe_key\":\"2025-08-09-Charlotte-Clemson\"}",
    "{\"game_id\":\"wmt-2025-08-12-Clemson-USC-Upstate\",\"date\":\"2025-08-12\",\"home_team_name\":\"Clemson\",\"away_team_name\":\"USC Upstate\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":null,\"away_score\":null,\"location_type\":\"home\",\"game_type\":\"exhibition\",\"status\":\"scheduled\",\"source_urls\":{\"schedule_url\":\"https://clemsontigers.com/sports/mens-soccer/schedule\"},\"dedupe_key\":\"2025-08-12-Clemson-USC-Upstate\"}",
    "{\"game_id\":\"wmt-2025-08-16-Clemson-Georgia-State\",\"date\":\"2025-08-16\",\"home_team_name\":\"Georgia State\",\"away_team_name\":\"Clemson\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":null,\"away_score\":null,\"location_type\":\"away\",\"game_type\":\"exhibition\",\"status\":\"scheduled\",\"source_urls\":{\"schedule_url\":\"https://clemsontigers.com/sports/mens-soccer/schedule\"},\"dedupe_key\":\"2025-08-16-Clemson-Georgia-State\"}",
    "{\"game_id\":\"wmt-2025-08-21-Clemson-Indiana\",\"date\":\"2025-08-21\",\"home_team_name\":\"Indiana\",\"away_team_name\":\"Clemson\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":2,\"away_score\":2,\"location_type\":\"away\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://clemsontigers.com/sports/mens-soccer/schedule\",\"boxscore_url\":\"https://clemsontigers.com/boxscore/316\"},\"dedupe_key\":\"2025-08-21-Clemson-Indiana\"}",
    "{\"game_id\":\"wmt-2025-08-26-Clemson-South-Carolina\",\"date\":\"2025-08-26\",\"home_team_name\":\"Clemson\",\"away_team_name\":\"South Carolina\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":4,\"away_score\":1,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://clemsontigers.com/sports/mens-soccer/schedule\",\"boxscore_url\":\"https://clemsontigers.com/boxscore/324\",\"recap_url\":\"https://clemsontigers.com/sc-recap/\"},\"dedupe_key\":\"2025-08-26-Clemson-South-Carolina\"}",
    "{\"game_id\":\"wmt-2025-08-29-Clemson-UAB\",\"date\":\"2025-08-29\",\"home_team_name\":\"Clemson\",\"away_team_name\":\"UAB\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":6,\"away_score\":0,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://clemsontigers.com/sports/mens-soccer/schedule\",\"boxscore_url\":\"https://clemsontigers.com/boxscore/321\",\"recap_url\":\"https://clemsontigers.com/no-6-tigers-down-uab-6-0-at-historic-riggs-field-friday-night/\"},\"dedupe_key\":\"2025-08-29-Clemson-UAB\"}",
    "{\"game_id\":\"wmt-2025-09-05-Clemson-Pittsburgh\",\"date\":\"2025-09-05\",\"home_team_name\":\"Clemson\",\"away_team_name\":\"Pittsburgh\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":3,\"away_score\":2,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://clemsontigers.com/sports/mens-soccer/schedule\",\"boxscore_url\":\"https://clemsontigers.com/boxscore/317\",\"recap_url\":\"https://clemsontigers.com/no-3-clemson-tops-no-10-pitt-in-friday-night-action/\"},\"dedupe_key\":\"2025-09-05-Clemson-Pittsburgh\"}",
    "{\"game_id\":\"wmt-2025-09-09-Clemson-VCU\",\"date\":\"2025-09-09\",\"home_team_name\":\"Clemson\",\"away_team_name\":\"VCU\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":1,\"away_score\":2,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://clemsontigers.com/sports/mens-soccer/schedule\",\"boxscore_url\":\"https://clemsontigers.com/boxscore/310\",\"recap_url\":\"https://clemsontigers.com/no-2-clemson-falls-to-vcu-tuesday-night/\"},\"dedupe_key\":\"2025-09-09-Clemson-VCU\"}",
    "{\"game_id\":\"wmt-2025-09-13-Clemson-SMU\",\"date\":\"2025-09-13\",\"home_team_name\":\"SMU\",\"away_team_name\":\"Clemson\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":1,\"away_score\":1,\"location_type\":\"away\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://clemsontigers.com/sports/mens-soccer/schedule\",\"boxscore_url\":\"https://clemsontigers.com/boxscore/318\",\"recap_url\":\"https://clemsontigers.com/no-2-tigers-and-smu-draw-1-1-saturday-night/\"},\"dedupe_key\":\"2025-09-13-Clemson-SMU\"}",
    "{\"game_id\":\"wmt-2025-09-16-Clemson-Queens\",\"date\":\"2025-09-16\",\"home_team_name\":\"Clemson\",\"away_team_name\":\"Queens\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":0,\"away_score\":1,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://clemsontigers.com/sports/mens-soccer/schedule\",\"boxscore_url\":\"https://clemsontigers.com/boxscore/326\",\"recap_url\":\"https://clemsontigers.com/no-14-tigers-fall-to-queens-tuesday-night/\"},\"dedupe_key\":\"2025-09-16-Clemson-Queens\"}",
    "{\"game_id\":\"wmt-2025-09-19-California-Clemson\",\"date\":\"2025-09-19\",\"home_team_name\":\"Clemson\",\"away_team_name\":\"California\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":3,\"away_score\":1,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://clemsontigers.com/sports/mens-soccer/schedule\",\"boxscore_url\":\"https://clemsontigers.com/boxscore/288\",\"recap_url\":\"https://clemsontigers.com/no-14-tigers-sail-past-cal-friday-night-with-a-3-1-win/\"},\"dedupe_key\":\"2025-09-19-California-Clemson\"}",
    "{\"game_id\":\"wmt-2025-09-26-Clemson-Wake-Forest\",\"date\":\"2025-09-26\",\"home_team_name\":\"Wake Forest\",\"away_team_name\":\"Clemson\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":3,\"away_score\":4,\"location_type\":\"away\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://clemsontigers.com/sports/mens-soccer/schedule\",\"boxscore_url\":\"https://clemsontigers.com/boxscore/289\",\"recap_url\":\"https://clemsontigers.com/tigers-win-a-4-3-thriller-at-no-13-wake-forest-friday-night/\"},\"dedupe_key\":\"2025-09-26-Clemson-Wake-Forest\"}",
    "{\"game_id\":\"wmt-2025-10-04-Clemson-Elon\",\"date\":\"2025-10-04\",\"home_team_name\":\"Clemson\",\"away_team_name\":\"Elon\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":1,\"away_score\":0,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://clemsontigers.com/sports/mens-soccer/schedule\",\"boxscore_url\":\"https://clemsontigers.com/boxscore/291\",\"recap_url\":\"https://clemsontigers.com/tigers-beat-elon-in-a-1-0-thriller-saturday-night/\"},\"dedupe_key\":\"2025-10-04-Clemson-Elon\"}",
    "{\"game_id\":\"wmt-2025-10-10-Clemson-NC-State\",\"date\":\"2025-10-10\",\"home_team_name\":\"NC State\",\"away_team_name\":\"Clemson\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":1,\"away_score\":0,\"location_type\":\"away\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://clemsontigers.com/sports/mens-soccer/schedule\",\"boxscore_url\":\"https://clemsontigers.com/boxscore/308\",\"recap_url\":\"https://clemsontigers.com/clemson-falls-1-0-to-no-10-n-c-state-on-the-road-friday-night/\"},\"dedupe_key\":\"2025-10-10-Clemson-NC-State\"}",
    "{\"game_id\":\"wmt-2025-10-17-Clemson-Duke\",\"date\":\"2025-10-17\",\"home_team_name\":\"Clemson\",\"away_team_name\":\"Duke\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":3,\"away_score\":0,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://clemsontigers.com/sports/mens-soccer/schedule\",\"boxscore_url\":\"https://clemsontigers.com/boxscore/325\",\"recap_url\":\"https://clemsontigers.com/tigers-upset-no-10-duke-3-0-friday-night/\"},\"dedupe_key\":\"2025-10-17-Clemson-Duke\"}",
    "{\"game_id\":\"wmt-2025-10-21-Clemson-UNC-Wilmington\",\"date\":\"2025-10-21\",\"home_team_name\":\"Clemson\",\"away_team_name\":\"UNC Wilmington\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":6,\"away_score\":0,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://clemsontigers.com/sports/mens-soccer/schedule\",\"boxscore_url\":\"https://clemsontigers.com/boxscore/311\",\"recap_url\":\"https://clemsontigers.com/tigers-run-over-uncw-6-0-tuesday-night/\"},\"dedupe_key\":\"2025-10-21-Clemson-UNC-Wilmington\"}",
    "{\"game_id\":\"wmt-2025-10-25-Clemson-Virginia\",\"date\":\"2025-10-25\",\"home_team_name\":\"Virginia\",\"away_team_name\":\"Clemson\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":4,\"away_score\":0,\"location_type\":\"away\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://clemsontigers.com/sports/mens-soccer/schedule\",\"boxscore_url\":\"https://clemsontigers.com/boxscore/320\",\"recap_url\":\"https://clemsontigers.com/no-10-tigers-fall-to-no-11-virginia-4-0-saturday-night/\"},\"dedupe_key\":\"2025-10-25-Clemson-Virginia\"}",
    "{\"game_id\":\"wmt-2025-10-31-Clemson-Virginia-Tech\",\"date\":\"2025-10-31\",\"home_team_name\":\"Clemson\",\"away_team_name\":\"Virginia Tech\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":3,\"away_score\":3,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://clemsontigers.com/sports/mens-soccer/schedule\",\"boxscore_url\":\"https://clemsontigers.com/boxscore/323\",\"recap_url\":\"https://clemsontigers.com/no-18-tigers-draw-3-3-with-virginia-tech-in-the-final-regular-season-match/\"},\"dedupe_key\":\"2025-10-31-Clemson-Virginia-Tech\"}",
    "{\"game_id\":\"wmt-2025-11-05-Clemson-Pittsburgh\",\"date\":\"2025-11-05\",\"home_team_name\":\"Clemson\",\"away_team_name\":\"Pittsburgh\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":0,\"away_score\":1,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://clemsontigers.com/sports/mens-soccer/schedule\",\"boxscore_url\":\"https://clemsontigers.com/boxscore/48\",\"recap_url\":\"https://clemsontigers.com/clemson-falls-to-pitt-1-0-in-the-first-round-of-the-acc-tournament/\"},\"dedupe_key\":\"2025-11-05-Clemson-Pittsburgh\"}",
    "{\"game_id\":\"wmt-2025-11-20-Clemson-Western-Michigan\",\"date\":\"2025-11-20\",\"home_team_name\":\"Clemson\",\"away_team_name\":\"Western Michigan\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":0,\"away_score\":1,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://clemsontigers.com/sports/mens-soccer/schedule\",\"boxscore_url\":\"https://clemsontigers.com/boxscore/9939\",\"recap_url\":\"https://clemsontigers.com/clemson-united-falls-1-0-to-western-michigan-in-round-one-of-the-ncaa-tournament/\"},\"dedupe_key\":\"2025-11-20-Clemson-Western-Michigan\"}"
];


/** Kentucky's 2025 season, WordPress `.schedule-item` theme. */
const KENTUCKY_SCHEDULE: string[] = [
    "{\"game_id\":\"wmtwp-2025-08-09-Kentucky-Lipscomb\",\"date\":\"2025-08-09\",\"home_team_name\":\"Kentucky\",\"away_team_name\":\"Lipscomb\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":null,\"away_score\":null,\"location_type\":\"home\",\"status\":\"scheduled\",\"source_urls\":{\"schedule_url\":\"https://ukathletics.com/sports/msoc/schedule/2025\"},\"dedupe_key\":\"2025-08-09-Kentucky-Lipscomb\"}",
    "{\"game_id\":\"wmtwp-2025-08-16-Kentucky-Northern-Kentucky\",\"date\":\"2025-08-16\",\"home_team_name\":\"Northern Kentucky\",\"away_team_name\":\"Kentucky\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":null,\"away_score\":null,\"location_type\":\"away\",\"status\":\"scheduled\",\"source_urls\":{\"schedule_url\":\"https://ukathletics.com/sports/msoc/schedule/2025\"},\"dedupe_key\":\"2025-08-16-Kentucky-Northern-Kentucky\"}",
    "{\"game_id\":\"wmtwp-2025-08-21-Kentucky-Western-Michigan\",\"date\":\"2025-08-21\",\"home_team_name\":\"Western Michigan\",\"away_team_name\":\"Kentucky\",\"home_team_ranked\":true,\"away_team_ranked\":false,\"home_score\":1,\"away_score\":2,\"location_type\":\"away\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://ukathletics.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://storage.googleapis.com/ukathletics-com/2025/08/ee7337dc-uk-msoc-box-score-western-michigan.pdf\",\"recap_url\":\"https://ukathletics.com/news/2025/08/21/alex-ruiz-scores-brace-in-kentucky-debut-wildcats-top-western-michigan-2-1-in-season-opener/\"},\"dedupe_key\":\"2025-08-21-Kentucky-Western-Michigan\"}",
    "{\"game_id\":\"wmtwp-2025-08-25-Bellarmine-Kentucky\",\"date\":\"2025-08-25\",\"home_team_name\":\"Kentucky\",\"away_team_name\":\"Bellarmine\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":1,\"away_score\":0,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://ukathletics.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://storage.googleapis.com/ukathletics-com/2025/08/04f952aa-msoc-box-score-vs-bellarmine.pdf\",\"recap_url\":\"https://ukathletics.com/news/2025/08/25/brizuela-rescues-1-0-win-over-bellarmine-in-home-opener/\"},\"dedupe_key\":\"2025-08-25-Bellarmine-Kentucky\"}",
    "{\"game_id\":\"wmtwp-2025-09-01-Kentucky-UCLA\",\"date\":\"2025-09-01\",\"home_team_name\":\"Kentucky\",\"away_team_name\":\"UCLA\",\"home_team_ranked\":false,\"away_team_ranked\":true,\"home_score\":0,\"away_score\":0,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://ukathletics.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://storage.googleapis.com/ukathletics-com/2025/09/7de69a6a-msoc-box-score-vs.-ucla.pdf\",\"recap_url\":\"https://ukathletics.com/news/2025/09/01/wildcats-held-to-scoreless-draw-vs-ucla/\"},\"dedupe_key\":\"2025-09-01-Kentucky-UCLA\"}",
    "{\"game_id\":\"wmtwp-2025-09-09-Detroit-Mercy-Kentucky\",\"date\":\"2025-09-09\",\"home_team_name\":\"Kentucky\",\"away_team_name\":\"Detroit Mercy\",\"home_team_ranked\":false,\"away_team_ranked\":true,\"home_score\":4,\"away_score\":0,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://ukathletics.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://storage.googleapis.com/ukathletics-com/2025/09/3bcdffee-msoc-box-score-vs-detroit-mercy.pdf\",\"recap_url\":\"https://ukathletics.com/news/2025/09/10/alex-ruizs-hat-trick-propels-wildcats-past-detroit-mercy/\"},\"dedupe_key\":\"2025-09-09-Detroit-Mercy-Kentucky\"}",
    "{\"game_id\":\"wmtwp-2025-09-14-Bowling-Green-Kentucky\",\"date\":\"2025-09-14\",\"home_team_name\":\"Kentucky\",\"away_team_name\":\"Bowling Green\",\"home_team_ranked\":false,\"away_team_ranked\":true,\"home_score\":1,\"away_score\":1,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://ukathletics.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://storage.googleapis.com/ukathletics-com/2025/09/d6f87e54-msoc-box-score-vs.-bowling-green.pdf\",\"recap_url\":\"https://ukathletics.com/news/2025/09/14/bertil-alban-scores-in-second-consecutive-match-kentucky-draws-1-1-vs-bowling-green/\"},\"dedupe_key\":\"2025-09-14-Bowling-Green-Kentucky\"}",
    "{\"game_id\":\"wmtwp-2025-09-19-Kentucky-UCF\",\"date\":\"2025-09-19\",\"home_team_name\":\"Kentucky\",\"away_team_name\":\"UCF\",\"home_team_ranked\":false,\"away_team_ranked\":true,\"home_score\":3,\"away_score\":2,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://ukathletics.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://storage.googleapis.com/ukathletics-com/2025/09/aacf289f-msoc-box-score-vs.-ucf.pdf\",\"recap_url\":\"https://ukathletics.com/news/2025/09/20/wildcats-outlast-ucf-in-3-2-thriller-in-sun-belt-opener/\"},\"dedupe_key\":\"2025-09-19-Kentucky-UCF\"}",
    "{\"game_id\":\"wmtwp-2025-09-23-Kentucky-Louisville\",\"date\":\"2025-09-23\",\"home_team_name\":\"Louisville\",\"away_team_name\":\"Kentucky\",\"home_team_ranked\":true,\"away_team_ranked\":false,\"home_score\":2,\"away_score\":2,\"location_type\":\"away\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://ukathletics.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://storage.googleapis.com/ukathletics-com/2025/09/224a1861-msoc-box-score-at-louisville.pdf\",\"recap_url\":\"https://ukathletics.com/news/2025/09/23/wildcats-suffer-late-equalizer-in-2-2-draw-at-louisville/\"},\"dedupe_key\":\"2025-09-23-Kentucky-Louisville\"}",
    "{\"game_id\":\"wmtwp-2025-09-28-Coastal-Carolina-Kentucky\",\"date\":\"2025-09-28\",\"home_team_name\":\"Coastal Carolina\",\"away_team_name\":\"Kentucky\",\"home_team_ranked\":true,\"away_team_ranked\":false,\"home_score\":0,\"away_score\":2,\"location_type\":\"away\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://ukathletics.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://storage.googleapis.com/ukathletics-com/2025/09/96ce3a2f-msoc-box-score-vs.-coastal-carolina.pdf\",\"recap_url\":\"https://ukathletics.com/news/2025/09/29/agustin-lopez-scores-brace-wildcats-win-2-0-at-coastal-carolina/\"},\"dedupe_key\":\"2025-09-28-Coastal-Carolina-Kentucky\"}",
    "{\"game_id\":\"wmtwp-2025-10-04-James-Madison-Kentucky\",\"date\":\"2025-10-04\",\"home_team_name\":\"Kentucky\",\"away_team_name\":\"James Madison\",\"home_team_ranked\":false,\"away_team_ranked\":true,\"home_score\":2,\"away_score\":0,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://ukathletics.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://storage.googleapis.com/ukathletics-com/2025/10/4c639302-msoc-box-score-vs.-jmu.pdf\",\"recap_url\":\"https://ukathletics.com/news/2025/10/04/isaiah-chisolms-brace-sends-kentucky-past-james-madison/\"},\"dedupe_key\":\"2025-10-04-James-Madison-Kentucky\"}",
    "{\"game_id\":\"wmtwp-2025-10-10-Kentucky-Marshall\",\"date\":\"2025-10-10\",\"home_team_name\":\"Marshall\",\"away_team_name\":\"Kentucky\",\"home_team_ranked\":true,\"away_team_ranked\":false,\"home_score\":4,\"away_score\":1,\"location_type\":\"away\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://ukathletics.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://storage.googleapis.com/ukathletics-com/2025/10/fdcc4789-msoc-box-score-marshall.pdf\",\"recap_url\":\"https://ukathletics.com/news/2025/10/10/wildcats-fall-4-1-at-no-17-marshall/\"},\"dedupe_key\":\"2025-10-10-Kentucky-Marshall\"}",
    "{\"game_id\":\"wmtwp-2025-10-14-Indiana-Kentucky\",\"date\":\"2025-10-14\",\"home_team_name\":\"Kentucky\",\"away_team_name\":\"Indiana\",\"home_team_ranked\":false,\"away_team_ranked\":true,\"home_score\":1,\"away_score\":2,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://ukathletics.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://storage.googleapis.com/ukathletics-com/2025/10/e7573c59-msoc-box-score-indiana.pdf\",\"recap_url\":\"https://ukathletics.com/news/2025/10/15/kentucky-drops-heartbreaking-2-1-result-in-non-conference-finale-vs-no-14-indiana/\"},\"dedupe_key\":\"2025-10-14-Indiana-Kentucky\"}",
    "{\"game_id\":\"wmtwp-2025-10-19-Kentucky-South-Carolina\",\"date\":\"2025-10-19\",\"home_team_name\":\"Kentucky\",\"away_team_name\":\"South Carolina\",\"home_team_ranked\":false,\"away_team_ranked\":true,\"home_score\":2,\"away_score\":1,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://ukathletics.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://storage.googleapis.com/ukathletics-com/2025/10/fcd3c630-msoc-box-score-vs.-south-carolina.pdf\",\"recap_url\":\"https://ukathletics.com/news/2025/10/19/bains-smiths-81st-minute-winner-lifts-wildcats-over-gamecocks-in-come-from-behind-2-1-win/\"},\"dedupe_key\":\"2025-10-19-Kentucky-South-Carolina\"}",
    "{\"game_id\":\"wmtwp-2025-10-22-Georgia-Southern-Kentucky\",\"date\":\"2025-10-22\",\"home_team_name\":\"Georgia Southern\",\"away_team_name\":\"Kentucky\",\"home_team_ranked\":true,\"away_team_ranked\":false,\"home_score\":1,\"away_score\":2,\"location_type\":\"away\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://ukathletics.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://storage.googleapis.com/ukathletics-com/2025/10/1b3856d7-msoc-box-score-vs.-georgia-southern.pdf\",\"recap_url\":\"https://ukathletics.com/news/2025/10/22/kevin-larssons-brace-lifts-no-25-kentucky-to-2-1-upset-win-over-no-20-georgia-southern/\"},\"dedupe_key\":\"2025-10-22-Georgia-Southern-Kentucky\"}",
    "{\"game_id\":\"wmtwp-2025-10-26-Kentucky-West-Virginia\",\"date\":\"2025-10-26\",\"home_team_name\":\"Kentucky\",\"away_team_name\":\"West Virginia\",\"home_team_ranked\":false,\"away_team_ranked\":true,\"home_score\":1,\"away_score\":0,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://ukathletics.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://storage.googleapis.com/ukathletics-com/2025/10/ea5f5443-msoc-box-score-vs.-west-virginia.pdf\",\"recap_url\":\"https://ukathletics.com/news/2025/10/26/alex-ruizs-winner-sends-wildcats-to-top-of-sun-belt-table-in-1-0-win-over-no-10-west-virginia/\"},\"dedupe_key\":\"2025-10-26-Kentucky-West-Virginia\"}",
    "{\"game_id\":\"wmtwp-2025-10-31-Georgia-State-Kentucky\",\"date\":\"2025-10-31\",\"home_team_name\":\"Kentucky\",\"away_team_name\":\"Georgia State\",\"home_team_ranked\":false,\"away_team_ranked\":true,\"home_score\":1,\"away_score\":0,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://ukathletics.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://storage.googleapis.com/ukathletics-com/2025/10/f8cc2279-msoc-box-score-vs.-georgia-state.pdf\",\"recap_url\":\"https://ukathletics.com/news/2025/10/31/kentucky-clinches-sbc-regular-season-title-with-1-0-win-over-georgia-state/\"},\"dedupe_key\":\"2025-10-31-Georgia-State-Kentucky\"}",
    "{\"game_id\":\"wmtwp-2025-11-04-Kentucky-Old-Dominion\",\"date\":\"2025-11-04\",\"home_team_name\":\"Old Dominion\",\"away_team_name\":\"Kentucky\",\"home_team_ranked\":true,\"away_team_ranked\":false,\"home_score\":1,\"away_score\":1,\"location_type\":\"away\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://ukathletics.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://storage.googleapis.com/ukathletics-com/2025/11/822f26cc-msoc-box-score-vs.-odu.pdf\",\"recap_url\":\"https://ukathletics.com/news/2025/11/04/wildcats-draw-at-old-dominion-1-1-in-regular-season-finale/\"},\"dedupe_key\":\"2025-11-04-Kentucky-Old-Dominion\"}",
    "{\"game_id\":\"wmtwp-2025-11-09-Coastal-Carolina-Kentucky\",\"date\":\"2025-11-09\",\"home_team_name\":\"Kentucky\",\"away_team_name\":\"Coastal Carolina\",\"home_team_ranked\":false,\"away_team_ranked\":true,\"home_score\":0,\"away_score\":0,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://ukathletics.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://storage.googleapis.com/ukathletics-com/2025/11/995b31d9-msoc-box-score-vs.-coastal-carolina-sbc-tournament.pdf\",\"recap_url\":\"https://ukathletics.com/news/2025/11/09/sebastian-conlons-save-sends-kentucky-to-sbc-semifinal-in-shootout-win-over-coastal-carolina/\"},\"dedupe_key\":\"2025-11-09-Coastal-Carolina-Kentucky\"}",
    "{\"game_id\":\"wmtwp-2025-11-12-Kentucky-UCF\",\"date\":\"2025-11-12\",\"home_team_name\":\"Kentucky\",\"away_team_name\":\"UCF\",\"home_team_ranked\":false,\"away_team_ranked\":true,\"home_score\":0,\"away_score\":1,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://ukathletics.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://storage.googleapis.com/ukathletics-com/2025/11/503b4cb4-msoc-ucf-sbc-semifinal-box-score.pdf\",\"recap_url\":\"https://ukathletics.com/news/2025/11/12/no-19-kentucky-falls-in-sbc-semifinal-to-ucf/\"},\"dedupe_key\":\"2025-11-12-Kentucky-UCF\"}",
    "{\"game_id\":\"wmtwp-2025-11-20-Kentucky-Saint-Louis\",\"date\":\"2025-11-20\",\"home_team_name\":\"Kentucky\",\"away_team_name\":\"Saint Louis\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":1,\"away_score\":2,\"location_type\":\"neutral\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://ukathletics.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://storage.googleapis.com/ukathletics-com/2025/11/95490af8-msoc-box-score-vs.-saint-louis.pdf\",\"recap_url\":\"https://ukathletics.com/news/2025/11/21/wildcats-eliminated-from-ncaa-tournament-in-2-1-extra-time-loss-to-saint-louis/\"},\"dedupe_key\":\"2025-11-20-Kentucky-Saint-Louis\"}"
];


/** South Carolina's 2025 season, WordPress `.schedule-table_row` theme. */
const SOUTH_CAROLINA_SCHEDULE: string[] = [
    "{\"game_id\":\"wmtwp-2025-08-09-NC-State-South-Carolina\",\"date\":\"2025-08-09\",\"home_team_name\":\"NC State\",\"away_team_name\":\"South Carolina\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":null,\"away_score\":null,\"location_type\":\"away\",\"status\":\"scheduled\",\"source_urls\":{\"schedule_url\":\"https://gamecocksonline.com/sports/msoc/schedule/2025\"},\"dedupe_key\":\"2025-08-09-NC-State-South-Carolina\"}",
    "{\"game_id\":\"wmtwp-2025-08-16-South-Carolina-Wofford\",\"date\":\"2025-08-16\",\"home_team_name\":\"South Carolina\",\"away_team_name\":\"Wofford\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":null,\"away_score\":null,\"location_type\":\"home\",\"status\":\"scheduled\",\"source_urls\":{\"schedule_url\":\"https://gamecocksonline.com/sports/msoc/schedule/2025\"},\"dedupe_key\":\"2025-08-16-South-Carolina-Wofford\"}",
    "{\"game_id\":\"wmtwp-2025-08-21-Charleston-South-Carolina\",\"date\":\"2025-08-21\",\"home_team_name\":\"Charleston\",\"away_team_name\":\"South Carolina\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":2,\"away_score\":3,\"location_type\":\"away\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://gamecocksonline.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://gamecocksonline.com/boxscore/charleston-8-21-2025/\",\"recap_url\":\"https://gamecocksonline.com/news/2025/08/21/three-second-half-goals-power-gamecocks-to-season-opening-win/\"},\"dedupe_key\":\"2025-08-21-Charleston-South-Carolina\"}",
    "{\"game_id\":\"wmtwp-2025-08-26-Clemson-South-Carolina\",\"date\":\"2025-08-26\",\"home_team_name\":\"Clemson\",\"away_team_name\":\"South Carolina\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":4,\"away_score\":1,\"location_type\":\"away\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://gamecocksonline.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://gamecocksonline.com/boxscore/clemson-525/\",\"recap_url\":\"https://gamecocksonline.com/news/2025/08/26/gamecocks-drop-road-match-to-tigers-2/\"},\"dedupe_key\":\"2025-08-26-Clemson-South-Carolina\"}",
    "{\"game_id\":\"wmtwp-2025-08-29-South-Carolina-USC-Upstate\",\"date\":\"2025-08-29\",\"home_team_name\":\"South Carolina\",\"away_team_name\":\"USC Upstate\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":1,\"away_score\":2,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://gamecocksonline.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://gamecocksonline.com/boxscore/usc-upstate-46/\",\"recap_url\":\"https://gamecocksonline.com/news/2025/08/29/gamecocks-drop-home-opener/\"},\"dedupe_key\":\"2025-08-29-South-Carolina-USC-Upstate\"}",
    "{\"game_id\":\"wmtwp-2025-09-02-FIU-South-Carolina\",\"date\":\"2025-09-02\",\"home_team_name\":\"South Carolina\",\"away_team_name\":\"FIU\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":3,\"away_score\":2,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://gamecocksonline.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://gamecocksonline.com/boxscore/fiu-12/\",\"recap_url\":\"https://gamecocksonline.com/news/2025/09/02/trimnal-and-ballek-rally-gamecocks-past-fiu/\"},\"dedupe_key\":\"2025-09-02-FIU-South-Carolina\"}",
    "{\"game_id\":\"wmtwp-2025-09-05-Charlotte-South-Carolina\",\"date\":\"2025-09-05\",\"home_team_name\":\"South Carolina\",\"away_team_name\":\"Charlotte\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":2,\"away_score\":1,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://gamecocksonline.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://gamecocksonline.com/boxscore/charlotte-145/\",\"recap_url\":\"https://gamecocksonline.com/news/2025/09/05/second-half-goals-power-gamecocks-past-charlotte/\"},\"dedupe_key\":\"2025-09-05-Charlotte-South-Carolina\"}",
    "{\"game_id\":\"wmtwp-2025-09-09-South-Carolina-Winthrop\",\"date\":\"2025-09-09\",\"home_team_name\":\"South Carolina\",\"away_team_name\":\"Winthrop\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":5,\"away_score\":1,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://gamecocksonline.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://gamecocksonline.com/boxscore/winthrop-126/\",\"recap_url\":\"https://gamecocksonline.com/news/2025/09/09/gamecocks-net-five-goals-in-win-over-eagles/\"},\"dedupe_key\":\"2025-09-09-South-Carolina-Winthrop\"}",
    "{\"game_id\":\"wmtwp-2025-09-13-South-Carolina-UNC-Greensboro\",\"date\":\"2025-09-13\",\"home_team_name\":\"UNC Greensboro\",\"away_team_name\":\"South Carolina\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":1,\"away_score\":2,\"location_type\":\"away\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://gamecocksonline.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://gamecocksonline.com/boxscore/uncg/\",\"recap_url\":\"https://gamecocksonline.com/news/2025/09/13/gamecocks-take-down-no-11-uncg-on-the-road/\"},\"dedupe_key\":\"2025-09-13-South-Carolina-UNC-Greensboro\"}",
    "{\"game_id\":\"wmtwp-2025-09-16-North-Florida-South-Carolina\",\"date\":\"2025-09-16\",\"home_team_name\":\"South Carolina\",\"away_team_name\":\"North Florida\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":0,\"away_score\":2,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://gamecocksonline.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://gamecocksonline.com/boxscore/msoc-vs-north-florida-9-16-25/\",\"recap_url\":\"https://gamecocksonline.com/news/2025/09/16/gamecocks-fall-to-ospreys/\"},\"dedupe_key\":\"2025-09-16-North-Florida-South-Carolina\"}",
    "{\"game_id\":\"wmtwp-2025-09-19-Georgia-State-South-Carolina\",\"date\":\"2025-09-19\",\"home_team_name\":\"South Carolina\",\"away_team_name\":\"Georgia State\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":2,\"away_score\":2,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://gamecocksonline.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://gamecocksonline.com/boxscore/georgia-state-74/\",\"recap_url\":\"https://gamecocksonline.com/news/2025/09/19/gamecocks-open-conference-play-with-2-2-draw/\"},\"dedupe_key\":\"2025-09-19-Georgia-State-South-Carolina\"}",
    "{\"game_id\":\"wmtwp-2025-09-23-Queens-University-Charlotte-South-Carolina\",\"date\":\"2025-09-23\",\"home_team_name\":\"South Carolina\",\"away_team_name\":\"Queens University Charlotte\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":1,\"away_score\":0,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://gamecocksonline.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://gamecocksonline.com/boxscore/queens-university-charlotte/\",\"recap_url\":\"https://gamecocksonline.com/news/2025/09/23/velazquez-lopez-goal-leads-gamecocks-past-royals/\"},\"dedupe_key\":\"2025-09-23-Queens-University-Charlotte-South-Carolina\"}",
    "{\"game_id\":\"wmtwp-2025-09-28-James-Madison-South-Carolina\",\"date\":\"2025-09-28\",\"home_team_name\":\"James Madison\",\"away_team_name\":\"South Carolina\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":0,\"away_score\":1,\"location_type\":\"away\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://gamecocksonline.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://gamecocksonline.com/boxscore/james-madison-9/\",\"recap_url\":\"https://gamecocksonline.com/news/2025/09/28/habels-goal-in-final-minutes-gives-carolina-road-win/\"},\"dedupe_key\":\"2025-09-28-James-Madison-South-Carolina\"}",
    "{\"game_id\":\"wmtwp-2025-10-04-South-Carolina-UCF\",\"date\":\"2025-10-04\",\"home_team_name\":\"South Carolina\",\"away_team_name\":\"UCF\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":0,\"away_score\":2,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://gamecocksonline.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://gamecocksonline.com/boxscore/msoc-vs-ucf-10-4-25/\",\"recap_url\":\"https://gamecocksonline.com/news/2025/10/04/gamecocks-drop-match-to-ucf/\"},\"dedupe_key\":\"2025-10-04-South-Carolina-UCF\"}",
    "{\"game_id\":\"wmtwp-2025-10-10-Old-Dominion-South-Carolina\",\"date\":\"2025-10-10\",\"home_team_name\":\"South Carolina\",\"away_team_name\":\"Old Dominion\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":1,\"away_score\":1,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://gamecocksonline.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://gamecocksonline.com/boxscore/msoc-vs-old-dominion-10-10-25/\",\"recap_url\":\"https://gamecocksonline.com/news/2025/10/10/gamecocks-post-1-1-draw-against-odu/\"},\"dedupe_key\":\"2025-10-10-Old-Dominion-South-Carolina\"}",
    "{\"game_id\":\"wmtwp-2025-10-19-Kentucky-South-Carolina\",\"date\":\"2025-10-19\",\"home_team_name\":\"Kentucky\",\"away_team_name\":\"South Carolina\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":2,\"away_score\":1,\"location_type\":\"away\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://gamecocksonline.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://gamecocksonline.com/boxscore/msoc-at-kentucky-10-19-25/\",\"recap_url\":\"https://gamecocksonline.com/news/2025/10/19/gamecocks-drop-road-contest-to-no-25-wildcats/\"},\"dedupe_key\":\"2025-10-19-Kentucky-South-Carolina\"}",
    "{\"game_id\":\"wmtwp-2025-10-22-Marshall-South-Carolina\",\"date\":\"2025-10-22\",\"home_team_name\":\"Marshall\",\"away_team_name\":\"South Carolina\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":4,\"away_score\":0,\"location_type\":\"away\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://gamecocksonline.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://gamecocksonline.com/boxscore/msoc-at-marshall-10-22-25/\",\"recap_url\":\"https://gamecocksonline.com/news/2025/10/22/gamecocks-fall-at-no-9-marshall/\"},\"dedupe_key\":\"2025-10-22-Marshall-South-Carolina\"}",
    "{\"game_id\":\"wmtwp-2025-10-26-Coastal-Carolina-South-Carolina\",\"date\":\"2025-10-26\",\"home_team_name\":\"South Carolina\",\"away_team_name\":\"Coastal Carolina\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":1,\"away_score\":3,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://gamecocksonline.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://gamecocksonline.com/boxscore/msoc-vs-coastal-carolina-10-26-25/\",\"recap_url\":\"https://gamecocksonline.com/news/2025/10/26/early-goal-not-enough-for-gamecocks/\"},\"dedupe_key\":\"2025-10-26-Coastal-Carolina-South-Carolina\"}",
    "{\"game_id\":\"wmtwp-2025-10-31-Georgia-Southern-South-Carolina\",\"date\":\"2025-10-31\",\"home_team_name\":\"Georgia Southern\",\"away_team_name\":\"South Carolina\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":3,\"away_score\":1,\"location_type\":\"away\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://gamecocksonline.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://gamecocksonline.com/boxscore/msoc-at-georgia-southern-10-31-25/\",\"recap_url\":\"https://gamecocksonline.com/news/2025/10/31/gamecocks-drop-road-contest-to-eagles/\"},\"dedupe_key\":\"2025-10-31-Georgia-Southern-South-Carolina\"}",
    "{\"game_id\":\"wmtwp-2025-11-04-South-Carolina-West-Virginia\",\"date\":\"2025-11-04\",\"home_team_name\":\"South Carolina\",\"away_team_name\":\"West Virginia\",\"home_team_ranked\":false,\"away_team_ranked\":false,\"home_score\":1,\"away_score\":2,\"location_type\":\"home\",\"status\":\"final\",\"source_urls\":{\"schedule_url\":\"https://gamecocksonline.com/sports/msoc/schedule/2025\",\"boxscore_url\":\"https://gamecocksonline.com/boxscore/msoc-vs-west-virginia-11-4-25/\",\"recap_url\":\"https://gamecocksonline.com/news/2025/11/04/mens-soccer-season-comes-to-a-close-to-no-16-west-virginia/\"},\"dedupe_key\":\"2025-11-04-South-Carolina-West-Virginia\"}"
];


/** Clemson 4-1 South Carolina, as the stats payload states it. */
const WMT_BOXSCORE_GAME = "{\"home_team_name\":\"Clemson\",\"away_team_name\":\"South Carolina\",\"home_score\":4,\"away_score\":1}";


/** Both squads from `api.wmt.games`: 36 players, seconds converted to whole minutes,
 * keepers read off `sGoalkeeperMinutesPlayed` where the field counter is absent. */
const WMT_BOXSCORE: string[] = [
    "{\"game_id\":\"wmt-6391107\",\"team_id\":\"Clemson\",\"player_name\":\"Yoshizawa, Misei\",\"player_key\":\"clemson:yoshizawamisei\",\"jersey_number\":\"11\",\"minutes\":72,\"goals\":1,\"assists\":1,\"shots\":3,\"stats\":{\"shots_on_goal\":1,\"saves\":0,\"goals_allowed\":0,\"fouls\":1,\"yellow_cards\":0,\"red_cards\":0,\"position\":\"M\",\"started\":1}}",
    "{\"game_id\":\"wmt-6391107\",\"team_id\":\"Clemson\",\"player_name\":\"Kelly, James\",\"player_key\":\"clemson:kellyjames\",\"jersey_number\":\"19\",\"minutes\":18,\"goals\":0,\"assists\":0,\"shots\":2,\"stats\":{\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0,\"fouls\":1,\"yellow_cards\":0,\"red_cards\":0,\"position\":\"F\",\"started\":0}}",
    "{\"game_id\":\"wmt-6391107\",\"team_id\":\"Clemson\",\"player_name\":\"Richmond, Nathan\",\"player_key\":\"clemson:richmondnathan\",\"jersey_number\":\"25\",\"minutes\":66,\"goals\":1,\"assists\":0,\"shots\":5,\"stats\":{\"shots_on_goal\":2,\"saves\":0,\"goals_allowed\":0,\"fouls\":1,\"yellow_cards\":0,\"red_cards\":0,\"position\":\"M\",\"started\":1}}",
    "{\"game_id\":\"wmt-6391107\",\"team_id\":\"Clemson\",\"player_name\":\"Andema, Joseph\",\"player_key\":\"clemson:andemajoseph\",\"jersey_number\":\"1\",\"minutes\":90,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"shots_on_goal\":0,\"saves\":2,\"goals_allowed\":1,\"fouls\":0,\"yellow_cards\":0,\"red_cards\":0,\"position\":\"GK\",\"started\":1}}",
    "{\"game_id\":\"wmt-6391107\",\"team_id\":\"Clemson\",\"player_name\":\"Leib, Matthias\",\"player_key\":\"clemson:leibmatthias\",\"jersey_number\":\"18\",\"minutes\":83,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0,\"fouls\":0,\"yellow_cards\":0,\"red_cards\":0,\"position\":\"D\",\"started\":0}}",
    "{\"game_id\":\"wmt-6391107\",\"team_id\":\"Clemson\",\"player_name\":\"Jimenez, Mason\",\"player_key\":\"clemson:jimenezmason\",\"jersey_number\":\"16\",\"minutes\":90,\"goals\":0,\"assists\":1,\"shots\":1,\"stats\":{\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0,\"fouls\":1,\"yellow_cards\":0,\"red_cards\":0,\"position\":\"M\",\"started\":1}}",
    "{\"game_id\":\"wmt-6391107\",\"team_id\":\"Clemson\",\"player_name\":\"Duquenne, Arthur\",\"player_key\":\"clemson:duquennearthur\",\"jersey_number\":\"3\",\"minutes\":90,\"goals\":0,\"assists\":0,\"shots\":1,\"stats\":{\"shots_on_goal\":1,\"saves\":0,\"goals_allowed\":0,\"fouls\":0,\"yellow_cards\":0,\"red_cards\":0,\"position\":\"D\",\"started\":1}}",
    "{\"game_id\":\"wmt-6391107\",\"team_id\":\"Clemson\",\"player_name\":\"Okunlola, Remi\",\"player_key\":\"clemson:okunlolaremi\",\"jersey_number\":\"30\",\"minutes\":90,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0,\"fouls\":0,\"yellow_cards\":0,\"red_cards\":0,\"position\":\"F\",\"started\":1}}",
    "{\"game_id\":\"wmt-6391107\",\"team_id\":\"Clemson\",\"player_name\":\"Musah, Wahabu\",\"player_key\":\"clemson:musahwahabu\",\"jersey_number\":\"7\",\"minutes\":37,\"goals\":1,\"assists\":0,\"shots\":4,\"stats\":{\"shots_on_goal\":1,\"saves\":0,\"goals_allowed\":0,\"fouls\":0,\"yellow_cards\":0,\"red_cards\":0,\"position\":\"F\",\"started\":1}}",
    "{\"game_id\":\"wmt-6391107\",\"team_id\":\"Clemson\",\"player_name\":\"Gyan, Ransford\",\"player_key\":\"clemson:gyanransford\",\"jersey_number\":\"10\",\"minutes\":65,\"goals\":1,\"assists\":0,\"shots\":5,\"stats\":{\"shots_on_goal\":2,\"saves\":0,\"goals_allowed\":0,\"fouls\":1,\"yellow_cards\":0,\"red_cards\":0,\"position\":\"F\",\"started\":1}}",
    "{\"game_id\":\"wmt-6391107\",\"team_id\":\"Clemson\",\"player_name\":\"Magnason, Lukas\",\"player_key\":\"clemson:magnasonlukas\",\"jersey_number\":\"2\",\"minutes\":90,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0,\"fouls\":0,\"yellow_cards\":0,\"red_cards\":0,\"position\":\"D\",\"started\":1}}",
    "{\"game_id\":\"wmt-6391107\",\"team_id\":\"Clemson\",\"player_name\":\"Stephensen, Olafur Floki\",\"player_key\":\"clemson:stephensenolafurfloki\",\"jersey_number\":\"4\",\"minutes\":90,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0,\"fouls\":0,\"yellow_cards\":0,\"red_cards\":0,\"position\":\"D\",\"started\":1}}",
    "{\"game_id\":\"wmt-6391107\",\"team_id\":\"Clemson\",\"player_name\":\"Beirute, Andres\",\"player_key\":\"clemson:beiruteandres\",\"jersey_number\":\"20\",\"minutes\":2,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0,\"fouls\":0,\"yellow_cards\":0,\"red_cards\":0,\"position\":\"F\",\"started\":0}}",
    "{\"game_id\":\"wmt-6391107\",\"team_id\":\"Clemson\",\"player_name\":\"Hineline, Cooper\",\"player_key\":\"clemson:hinelinecooper\",\"jersey_number\":\"14\",\"minutes\":4,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0,\"fouls\":0,\"yellow_cards\":0,\"red_cards\":0,\"position\":\"M\",\"started\":0}}",
    "{\"game_id\":\"wmt-6391107\",\"team_id\":\"Clemson\",\"player_name\":\"Mane, Abdou\",\"player_key\":\"clemson:maneabdou\",\"jersey_number\":\"15\",\"minutes\":23,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0,\"fouls\":0,\"yellow_cards\":0,\"red_cards\":0,\"position\":\"M\",\"started\":0}}",
    "{\"game_id\":\"wmt-6391107\",\"team_id\":\"Clemson\",\"player_name\":\"Sevian, Xander\",\"player_key\":\"clemson:sevianxander\",\"jersey_number\":\"28\",\"minutes\":23,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0,\"fouls\":0,\"yellow_cards\":0,\"red_cards\":0,\"position\":\"F\",\"started\":0}}",
    "{\"game_id\":\"wmt-6391107\",\"team_id\":\"Clemson\",\"player_name\":\"Santuari, Gabriel\",\"player_key\":\"clemson:santuarigabriel\",\"jersey_number\":\"21\",\"minutes\":86,\"goals\":0,\"assists\":1,\"shots\":2,\"stats\":{\"shots_on_goal\":2,\"saves\":0,\"goals_allowed\":0,\"fouls\":0,\"yellow_cards\":0,\"red_cards\":0,\"position\":\"F\",\"started\":1}}",
    "{\"game_id\":\"wmt-6391107\",\"team_id\":\"Clemson\",\"player_name\":\"Bunk, Daniel\",\"player_key\":\"clemson:bunkdaniel\",\"jersey_number\":\"6\",\"minutes\":15,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0,\"fouls\":0,\"yellow_cards\":0,\"red_cards\":0,\"position\":\"D\",\"started\":0}}",
    "{\"game_id\":\"wmt-6391107\",\"team_id\":\"South Carolina\",\"player_name\":\"Goldsworthy, Andrew\",\"player_key\":\"southcarolina:goldsworthyandrew\",\"jersey_number\":\"2\",\"minutes\":90,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0,\"fouls\":0,\"yellow_cards\":0,\"red_cards\":0,\"position\":\"D\",\"started\":1}}",
    "{\"game_id\":\"wmt-6391107\",\"team_id\":\"South Carolina\",\"player_name\":\"Flynn, Galen\",\"player_key\":\"southcarolina:flynngalen\",\"jersey_number\":\"18\",\"minutes\":15,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0,\"fouls\":0,\"yellow_cards\":0,\"red_cards\":0,\"position\":\"D\",\"started\":0}}",
    "{\"game_id\":\"wmt-6391107\",\"team_id\":\"South Carolina\",\"player_name\":\"Nilsson, William\",\"player_key\":\"southcarolina:nilssonwilliam\",\"jersey_number\":\"5\",\"minutes\":77,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0,\"fouls\":1,\"yellow_cards\":0,\"red_cards\":0,\"position\":\"D\",\"started\":1}}",
    "{\"game_id\":\"wmt-6391107\",\"team_id\":\"South Carolina\",\"player_name\":\"Ballek, Ethan\",\"player_key\":\"southcarolina:ballekethan\",\"jersey_number\":\"10\",\"minutes\":52,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0,\"fouls\":0,\"yellow_cards\":0,\"red_cards\":0,\"position\":\"M\",\"started\":1}}",
    "{\"game_id\":\"wmt-6391107\",\"team_id\":\"South Carolina\",\"player_name\":\"Cargill, Ted\",\"player_key\":\"southcarolina:cargillted\",\"jersey_number\":\"22\",\"minutes\":31,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0,\"fouls\":0,\"yellow_cards\":0,\"red_cards\":0,\"position\":\"M\",\"started\":1}}",
    "{\"game_id\":\"wmt-6391107\",\"team_id\":\"South Carolina\",\"player_name\":\"Kolby, Samy\",\"player_key\":\"southcarolina:kolbysamy\",\"jersey_number\":\"17\",\"minutes\":37,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0,\"fouls\":0,\"yellow_cards\":0,\"red_cards\":0,\"position\":\"M\",\"started\":1}}",
    "{\"game_id\":\"wmt-6391107\",\"team_id\":\"South Carolina\",\"player_name\":\"Trimnal, Tyler\",\"player_key\":\"southcarolina:trimnaltyler\",\"jersey_number\":\"9\",\"minutes\":58,\"goals\":0,\"assists\":0,\"shots\":2,\"stats\":{\"shots_on_goal\":2,\"saves\":0,\"goals_allowed\":0,\"fouls\":1,\"yellow_cards\":1,\"red_cards\":0,\"position\":\"F\",\"started\":1}}",
    "{\"game_id\":\"wmt-6391107\",\"team_id\":\"South Carolina\",\"player_name\":\"Stjernegaard, Alexander\",\"player_key\":\"southcarolina:stjernegaardalexander\",\"jersey_number\":\"8\",\"minutes\":70,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0,\"fouls\":0,\"yellow_cards\":0,\"red_cards\":0,\"position\":\"M\",\"started\":1}}",
    "{\"game_id\":\"wmt-6391107\",\"team_id\":\"South Carolina\",\"player_name\":\"Bigger, Jonah\",\"player_key\":\"southcarolina:biggerjonah\",\"jersey_number\":\"13\",\"minutes\":84,\"goals\":0,\"assists\":0,\"shots\":1,\"stats\":{\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0,\"fouls\":0,\"yellow_cards\":0,\"red_cards\":0,\"position\":\"M\",\"started\":1}}",
    "{\"game_id\":\"wmt-6391107\",\"team_id\":\"South Carolina\",\"player_name\":\"Habel, Mika\",\"player_key\":\"southcarolina:habelmika\",\"jersey_number\":\"6\",\"minutes\":75,\"goals\":1,\"assists\":0,\"shots\":1,\"stats\":{\"shots_on_goal\":1,\"saves\":0,\"goals_allowed\":0,\"fouls\":0,\"yellow_cards\":0,\"red_cards\":0,\"position\":\"M\",\"started\":1}}",
    "{\"game_id\":\"wmt-6391107\",\"team_id\":\"South Carolina\",\"player_name\":\"Whittaker-Francis, Isaiah\",\"player_key\":\"southcarolina:whittakerfrancisisaiah\",\"jersey_number\":\"7\",\"minutes\":59,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0,\"fouls\":1,\"yellow_cards\":0,\"red_cards\":0,\"position\":\"D\",\"started\":0}}",
    "{\"game_id\":\"wmt-6391107\",\"team_id\":\"South Carolina\",\"player_name\":\"Bader, Keanan\",\"player_key\":\"southcarolina:baderkeanan\",\"jersey_number\":\"19\",\"minutes\":59,\"goals\":0,\"assists\":0,\"shots\":1,\"stats\":{\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0,\"fouls\":0,\"yellow_cards\":0,\"red_cards\":0,\"position\":\"F\",\"started\":0}}",
    "{\"game_id\":\"wmt-6391107\",\"team_id\":\"South Carolina\",\"player_name\":\"Versterre, Filip\",\"player_key\":\"southcarolina:versterrefilip\",\"jersey_number\":\"1\",\"minutes\":90,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"shots_on_goal\":0,\"saves\":5,\"goals_allowed\":4,\"fouls\":0,\"yellow_cards\":0,\"red_cards\":0,\"position\":\"GK\",\"started\":1}}",
    "{\"game_id\":\"wmt-6391107\",\"team_id\":\"South Carolina\",\"player_name\":\"Velazquez-Lopez, Alejandro\",\"player_key\":\"southcarolina:velazquezlopezalejandro\",\"jersey_number\":\"15\",\"minutes\":59,\"goals\":0,\"assists\":0,\"shots\":1,\"stats\":{\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0,\"fouls\":1,\"yellow_cards\":0,\"red_cards\":0,\"position\":\"M\",\"started\":0}}",
    "{\"game_id\":\"wmt-6391107\",\"team_id\":\"South Carolina\",\"player_name\":\"Sany Kong, Loic\",\"player_key\":\"southcarolina:sanykongloic\",\"jersey_number\":\"11\",\"minutes\":51,\"goals\":0,\"assists\":0,\"shots\":1,\"stats\":{\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0,\"fouls\":0,\"yellow_cards\":0,\"red_cards\":0,\"position\":\"F\",\"started\":0}}",
    "{\"game_id\":\"wmt-6391107\",\"team_id\":\"South Carolina\",\"player_name\":\"DeJianne, Matthew\",\"player_key\":\"southcarolina:dejiannematthew\",\"jersey_number\":\"16\",\"minutes\":32,\"goals\":0,\"assists\":1,\"shots\":0,\"stats\":{\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0,\"fouls\":0,\"yellow_cards\":0,\"red_cards\":0,\"position\":\"F\",\"started\":0}}",
    "{\"game_id\":\"wmt-6391107\",\"team_id\":\"South Carolina\",\"player_name\":\"Cheetham, Jordan\",\"player_key\":\"southcarolina:cheethamjordan\",\"jersey_number\":\"24\",\"minutes\":6,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0,\"fouls\":0,\"yellow_cards\":0,\"red_cards\":0,\"position\":\"D\",\"started\":0}}",
    "{\"game_id\":\"wmt-6391107\",\"team_id\":\"South Carolina\",\"player_name\":\"Oddi, Riccardo\",\"player_key\":\"southcarolina:oddiriccardo\",\"jersey_number\":\"3\",\"minutes\":45,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0,\"fouls\":0,\"yellow_cards\":0,\"red_cards\":0,\"position\":\"D\",\"started\":1}}"
];


/**
 * The Sidearm box-score parser reports no game-level fields; the schedule row carries them.
 */
const SIDEARM_BOXSCORE_GAME = "{}";


/** Duke 2-0 Syracuse: both full squads, unused substitutes included on nil minutes.
 * Hut concedes the two, Dymora keeps the clean sheet — read the wrong keeper column and
 * the goals-allowed land on the winner. */
const SIDEARM_BOXSCORE: string[] = [
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Duke\",\"player_name\":\"Gallagher, Ryan\",\"player_key\":\"duke:gallagherryan\",\"jersey_number\":\"0\",\"minutes\":0,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"gk\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Duke\",\"player_name\":\"Dymora, Eryk\",\"player_key\":\"duke:dymoraeryk\",\"jersey_number\":\"1\",\"minutes\":90,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"gk\",\"shots_on_goal\":0,\"saves\":2,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Duke\",\"player_name\":\"Blakeney, Jackson\",\"player_key\":\"duke:blakeneyjackson\",\"jersey_number\":\"28\",\"minutes\":0,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"gk\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Duke\",\"player_name\":\"Gaviser, Nathan\",\"player_key\":\"duke:gavisernathan\",\"jersey_number\":\"30\",\"minutes\":0,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"gk\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Duke\",\"player_name\":\"Kabuusu, Jamie\",\"player_key\":\"duke:kabuusujamie\",\"jersey_number\":\"2\",\"minutes\":0,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Duke\",\"player_name\":\"Acito, Kamran\",\"player_key\":\"duke:acitokamran\",\"jersey_number\":\"3\",\"minutes\":90,\"goals\":0,\"assists\":0,\"shots\":1,\"stats\":{\"position\":\"def\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Duke\",\"player_name\":\"Burns, Trevor\",\"player_key\":\"duke:burnstrevor\",\"jersey_number\":\"4\",\"minutes\":60,\"goals\":0,\"assists\":1,\"shots\":0,\"stats\":{\"position\":\"mid\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Duke\",\"player_name\":\"Hauschild, Alex\",\"player_key\":\"duke:hauschildalex\",\"jersey_number\":\"5\",\"minutes\":0,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"def\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Duke\",\"player_name\":\"Vukovic, Aleksandar\",\"player_key\":\"duke:vukovicaleksandar\",\"jersey_number\":\"6\",\"minutes\":76,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"def\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Duke\",\"player_name\":\"Arlotti, Alessandro\",\"player_key\":\"duke:arlottialessandro\",\"jersey_number\":\"7\",\"minutes\":42,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"fwd\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Duke\",\"player_name\":\"Bull Jorgensen, Nikolai Ronaldo\",\"player_key\":\"duke:bulljorgensennikolaironaldo\",\"jersey_number\":\"8\",\"minutes\":30,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Duke\",\"player_name\":\"Bjornsson, Ulfur\",\"player_key\":\"duke:bjornssonulfur\",\"jersey_number\":\"9\",\"minutes\":34,\"goals\":1,\"assists\":0,\"shots\":4,\"stats\":{\"position\":\"fwd\",\"shots_on_goal\":2,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Duke\",\"player_name\":\"Kerr, Drew\",\"player_key\":\"duke:kerrdrew\",\"jersey_number\":\"10\",\"minutes\":90,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"mid\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Duke\",\"player_name\":\"D'Ambrosio, Leonardo\",\"player_key\":\"duke:dambrosioleonardo\",\"jersey_number\":\"11\",\"minutes\":25,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"mid\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Duke\",\"player_name\":\"Vold, Thomas\",\"player_key\":\"duke:voldthomas\",\"jersey_number\":\"12\",\"minutes\":30,\"goals\":0,\"assists\":1,\"shots\":0,\"stats\":{\"position\":\"mid\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Duke\",\"player_name\":\"Ortega, Jose\",\"player_key\":\"duke:ortegajose\",\"jersey_number\":\"13\",\"minutes\":65,\"goals\":1,\"assists\":0,\"shots\":4,\"stats\":{\"position\":\"mid\",\"shots_on_goal\":2,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Duke\",\"player_name\":\"Racaj, Ari\",\"player_key\":\"duke:racajari\",\"jersey_number\":\"15\",\"minutes\":53,\"goals\":0,\"assists\":0,\"shots\":3,\"stats\":{\"position\":\"fwd\",\"shots_on_goal\":1,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Duke\",\"player_name\":\"Simpson, Maxwell\",\"player_key\":\"duke:simpsonmaxwell\",\"jersey_number\":\"16\",\"minutes\":74,\"goals\":0,\"assists\":2,\"shots\":2,\"stats\":{\"position\":\"mid\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Duke\",\"player_name\":\"Byasiima, Adrian\",\"player_key\":\"duke:byasiimaadrian\",\"jersey_number\":\"17\",\"minutes\":0,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"fwd\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Duke\",\"player_name\":\"Suber, Julius\",\"player_key\":\"duke:suberjulius\",\"jersey_number\":\"18\",\"minutes\":48,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"mid\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Duke\",\"player_name\":\"Hecker, Ian\",\"player_key\":\"duke:heckerian\",\"jersey_number\":\"19\",\"minutes\":0,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"mid\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Duke\",\"player_name\":\"Zabinko, Preston\",\"player_key\":\"duke:zabinkopreston\",\"jersey_number\":\"20\",\"minutes\":90,\"goals\":0,\"assists\":0,\"shots\":1,\"stats\":{\"position\":\"def\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Duke\",\"player_name\":\"Hill, Hugo\",\"player_key\":\"duke:hillhugo\",\"jersey_number\":\"21\",\"minutes\":0,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"mid\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Duke\",\"player_name\":\"Donaldson, Caleb\",\"player_key\":\"duke:donaldsoncaleb\",\"jersey_number\":\"22\",\"minutes\":0,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"mid\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Duke\",\"player_name\":\"Hot, Kenan\",\"player_key\":\"duke:hotkenan\",\"jersey_number\":\"23\",\"minutes\":90,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"mid\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Duke\",\"player_name\":\"Gudbjornsson, Axel\",\"player_key\":\"duke:gudbjornssonaxel\",\"jersey_number\":\"24\",\"minutes\":3,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"def\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Duke\",\"player_name\":\"Bag, Casey\",\"player_key\":\"duke:bagcasey\",\"jersey_number\":\"25\",\"minutes\":0,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"mid\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Duke\",\"player_name\":\"Smith, Tucker\",\"player_key\":\"duke:smithtucker\",\"jersey_number\":\"29\",\"minutes\":0,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"def\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Duke\",\"player_name\":\"Arbib, Sol\",\"player_key\":\"duke:arbibsol\",\"jersey_number\":\"31\",\"minutes\":0,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"fwd\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Duke\",\"player_name\":\"Lagos, Jackson\",\"player_key\":\"duke:lagosjackson\",\"jersey_number\":\"32\",\"minutes\":0,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"mid\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Syracuse\",\"player_name\":\"Jansen, Kyle\",\"player_key\":\"syracuse:jansenkyle\",\"jersey_number\":\"1\",\"minutes\":0,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"gk\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Syracuse\",\"player_name\":\"Hut, Tomas\",\"player_key\":\"syracuse:huttomas\",\"jersey_number\":\"25\",\"minutes\":90,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"gk\",\"shots_on_goal\":0,\"saves\":3,\"goals_allowed\":2}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Syracuse\",\"player_name\":\"Martinez-Bastidas, Juan\",\"player_key\":\"syracuse:martinezbastidasjuan\",\"jersey_number\":\"40\",\"minutes\":0,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"gk\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Syracuse\",\"player_name\":\"Omeze, Chimere\",\"player_key\":\"syracuse:omezechimere\",\"jersey_number\":\"2\",\"minutes\":47,\"goals\":0,\"assists\":0,\"shots\":2,\"stats\":{\"position\":\"def\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Syracuse\",\"player_name\":\"Mensah Jr., Ernest\",\"player_key\":\"syracuse:mensahjrernest\",\"jersey_number\":\"3\",\"minutes\":69,\"goals\":0,\"assists\":0,\"shots\":1,\"stats\":{\"position\":\"def\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Syracuse\",\"player_name\":\"Brdaric, Tim\",\"player_key\":\"syracuse:brdarictim\",\"jersey_number\":\"4\",\"minutes\":90,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"def\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Syracuse\",\"player_name\":\"Irinimbabazi, Ivan\",\"player_key\":\"syracuse:irinimbabaziivan\",\"jersey_number\":\"6\",\"minutes\":0,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Syracuse\",\"player_name\":\"Scott, Nathan\",\"player_key\":\"syracuse:scottnathan\",\"jersey_number\":\"7\",\"minutes\":77,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"mid\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Syracuse\",\"player_name\":\"Christey, Quentin\",\"player_key\":\"syracuse:christeyquentin\",\"jersey_number\":\"8\",\"minutes\":13,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Syracuse\",\"player_name\":\"Nutornutsi, Bright\",\"player_key\":\"syracuse:nutornutsibright\",\"jersey_number\":\"9\",\"minutes\":77,\"goals\":0,\"assists\":0,\"shots\":3,\"stats\":{\"position\":\"fwd\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Syracuse\",\"player_name\":\"Zambrano, Carlos\",\"player_key\":\"syracuse:zambranocarlos\",\"jersey_number\":\"10\",\"minutes\":58,\"goals\":0,\"assists\":0,\"shots\":1,\"stats\":{\"position\":\"mid\",\"shots_on_goal\":1,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Syracuse\",\"player_name\":\"Rodriguez, Bryson\",\"player_key\":\"syracuse:rodriguezbryson\",\"jersey_number\":\"11\",\"minutes\":0,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"mid\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Syracuse\",\"player_name\":\"Wigg, Gavin\",\"player_key\":\"syracuse:wigggavin\",\"jersey_number\":\"12\",\"minutes\":71,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"def\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Syracuse\",\"player_name\":\"Cappello, Emanuel\",\"player_key\":\"syracuse:cappelloemanuel\",\"jersey_number\":\"15\",\"minutes\":0,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"fwd\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Syracuse\",\"player_name\":\"Ibraheem, Faris\",\"player_key\":\"syracuse:ibraheemfaris\",\"jersey_number\":\"16\",\"minutes\":0,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"fwd\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Syracuse\",\"player_name\":\"Leibold, Giona\",\"player_key\":\"syracuse:leiboldgiona\",\"jersey_number\":\"17\",\"minutes\":44,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"mid\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Syracuse\",\"player_name\":\"Lugton, Callum\",\"player_key\":\"syracuse:lugtoncallum\",\"jersey_number\":\"18\",\"minutes\":0,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"fwd\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Syracuse\",\"player_name\":\"Acquah, Michael\",\"player_key\":\"syracuse:acquahmichael\",\"jersey_number\":\"19\",\"minutes\":34,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"fwd\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Syracuse\",\"player_name\":\"Noeding, Tim\",\"player_key\":\"syracuse:noedingtim\",\"jersey_number\":\"20\",\"minutes\":43,\"goals\":0,\"assists\":0,\"shots\":1,\"stats\":{\"position\":\"mid\",\"shots_on_goal\":1,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Syracuse\",\"player_name\":\"Darko, Landon\",\"player_key\":\"syracuse:darkolandon\",\"jersey_number\":\"21\",\"minutes\":13,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"mid\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Syracuse\",\"player_name\":\"Da Costa, Kelvin\",\"player_key\":\"syracuse:dacostakelvin\",\"jersey_number\":\"22\",\"minutes\":66,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"mid\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Syracuse\",\"player_name\":\"Ming, Sachiel\",\"player_key\":\"syracuse:mingsachiel\",\"jersey_number\":\"24\",\"minutes\":46,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Syracuse\",\"player_name\":\"Fortier, Kristjan\",\"player_key\":\"syracuse:fortierkristjan\",\"jersey_number\":\"26\",\"minutes\":62,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"mid\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Syracuse\",\"player_name\":\"Holman, Garrett\",\"player_key\":\"syracuse:holmangarrett\",\"jersey_number\":\"27\",\"minutes\":90,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"def\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}",
    "{\"game_id\":\"sidearm-24396\",\"team_id\":\"Syracuse\",\"player_name\":\"Frias, Santiago\",\"player_key\":\"syracuse:friassantiago\",\"jersey_number\":\"33\",\"minutes\":0,\"goals\":0,\"assists\":0,\"shots\":0,\"stats\":{\"position\":\"def\",\"shots_on_goal\":0,\"saves\":0,\"goals_allowed\":0}}"
];

test('Sidearm schedule HTML: Duke 2025 parses to 23 fixtures, in full', async () => {
    const games = await new SidearmParser().parseSchedule(fixture('sidearm_schedule_duke_2025.html'), {
        teamName: 'Duke',
        baseUrl: 'https://goduke.com/sports/mens-soccer/schedule/2025'
    });
    assert.deepEqual(lines(games), DUKE_SCHEDULE);
    assertValidGames(games);
});

test('WMT /website-api payload: Clemson 2025 parses to 20 fixtures, in full', () => {
    const payload = JSON.parse(fixture('wmt_schedule_events_clemson_2025.json'));
    assert.equal(payload.data.length, 25, 'the stored payload should still hold all 25 events');

    const games = new WmtParser().parseEvents(payload.data, {
        teamName: 'Clemson',
        baseUrl: 'https://clemsontigers.com/sports/mens-soccer/schedule',
        sourceUrl: 'https://clemsontigers.com/sports/mens-soccer/schedule',
        timeZone: 'America/New_York',
        nameResolver: resolver,
        seasonYear: 2025
    });
    assert.deepEqual(lines(games), CLEMSON_SCHEDULE);
    assertValidGames(games);
});

test('WMT WordPress, .schedule-item theme: Kentucky 2025 parses to 21 fixtures, in full', async () => {
    const games = await new WmtWordpressParser().parseSchedule(fixture('wordpress_schedule_kentucky_2025.html'), {
        teamName: 'Kentucky',
        baseUrl: 'https://ukathletics.com/sports/msoc/schedule',
        sourceUrl: 'https://ukathletics.com/sports/msoc/schedule/2025',
        nameResolver: resolver,
        seasonYear: 2025,
        timeZone: 'America/New_York'
    });
    assert.deepEqual(lines(games), KENTUCKY_SCHEDULE);
    assertValidGames(games);
});

test('WMT WordPress, .schedule-table_row theme: South Carolina 2025 parses to 20 fixtures, in full', async () => {
    const games = await new WmtWordpressParser().parseSchedule(fixture('wordpress_schedule_south_carolina_2025.html'), {
        teamName: 'South Carolina',
        baseUrl: 'https://gamecocksonline.com/sports/msoc/schedule',
        sourceUrl: 'https://gamecocksonline.com/sports/msoc/schedule/2025',
        nameResolver: resolver,
        seasonYear: 2025,
        timeZone: 'America/New_York'
    });
    assert.deepEqual(lines(games), SOUTH_CAROLINA_SCHEDULE);
    assertValidGames(games);
});

test('api.wmt.games stats payload: Clemson 4-1 South Carolina yields 36 player rows, in full', () => {
    const result = new WmtBoxScoreParser().parseStats(
        JSON.parse(fixture('wmt_stats_clemson_south_carolina_2025.json')),
        { nameResolver: resolver }
    );
    assert.equal(JSON.stringify(result.game), WMT_BOXSCORE_GAME);
    assert.deepEqual(lines(result.playerStats), WMT_BOXSCORE);
    assertValidPlayerStats(result.playerStats);
});

test('Sidearm box-score HTML: Duke 2-0 Syracuse yields 55 player rows, in full', () => {
    const result = new SidearmBoxScoreParser().parse(fixture('sidearm_boxscore_duke_syracuse_2025.html'), {
        sourceUrl: 'https://goduke.com/sports/mens-soccer/stats/2025/syracuse/boxscore/24396'
    });
    assert.equal(JSON.stringify(result.game), SIDEARM_BOXSCORE_GAME);
    assert.deepEqual(lines(result.playerStats), SIDEARM_BOXSCORE);
    assertValidPlayerStats(result.playerStats);
});

/**
 * The two box scores agree with the two schedules on the same fixture.
 *
 * Each half of this is asserted above already; what it adds is the join. A parser can be
 * internally consistent and still put the goals on the wrong side, and the only place
 * that shows is where two sources describe one game — Clemson's schedule row says it beat
 * South Carolina 4-1 at home, and the stats feed for that game has to say the same. This
 * is also the check that survives a fixture refresh, since it compares two files rather
 * than either file to a literal.
 */
test('the schedule row and the box score tell the same story about one fixture', () => {
    const clemson = CLEMSON_SCHEDULE.map(line => JSON.parse(line) as Game).find(
        game => game.date === '2025-08-26'
    );
    assert.ok(clemson, 'Clemson v South Carolina should be in the parsed schedule');

    const box = new WmtBoxScoreParser().parseStats(
        JSON.parse(fixture('wmt_stats_clemson_south_carolina_2025.json')),
        { nameResolver: resolver }
    );

    assert.equal(clemson.home_team_name, box.game.home_team_name);
    assert.equal(clemson.away_team_name, box.game.away_team_name);
    assert.equal(clemson.home_score, box.game.home_score);
    assert.equal(clemson.away_score, box.game.away_score);

    // The scorers add up to the scoreline: a box score that dropped one team's rows would
    // still parse, and would still look like a box score.
    const goals = (team: string): number =>
        box.playerStats
            .filter(stat => stat.team_id === team)
            .reduce((sum, stat) => sum + (stat.goals || 0), 0);
    assert.equal(goals('Clemson'), 4);
    assert.equal(goals('South Carolina'), 1);
});
